project:
  type: website
  output-dir: docs

website:
  title: "Jack Susank"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: TidyTuesday1.qmd
        text: Water Insecurity
      - href: TidyTuesday2.qmd
        text: Cheese!

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

