project:
  type: website
  output-dir: docs

website:
  title: "Jack Susank"
  navbar:
    left:
      - href: index.html
        text: Home
      - text: "Resume"
        href: 2_5_25 Resume (1).pdf
      - text: "Data Viz"
        menu: 
          - href: TidyTuesday1.html
            text: Water Insecurity
          - href: TidyTuesday2.html
            text: Cheese!

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

