---
title: "Cheese!"
description: |
  Analysis of Cheese data from TidyTuesday
author: Jack Susank
date: February 15, 2025
format: html
echo: FALSE
execute:
  warning: false
  message: false
---

This is an analysis of Cheese data sourced from TidyTuesday's June 4th, 2024 data release. The plot compares the fat and calcium contents different types of cheese. To download the data, visit [this github repo](https://github.com/rfordatascience/tidytuesday/blob/main/data/2024/2024-06-04/readme.md).
This dataset was compiled using data from [Cheese.com](https://www.cheese.com/) and its creation was inspired by the [polite package](https://dmi3kno.github.io/polite/).


```{r}
tuesdata <- tidytuesdayR::tt_load(2024, week = 23)

cheeses <- tuesdata$cheeses
```

```{r}
library(ggplot2)
library(stringr)
library(dplyr)


cleaned_cheeses <- cheeses |>
  select(fat_content, calcium_content) |>
  mutate(calcium_content = as.integer(str_replace(calcium_content, " mg/100g", ""))) |>
  mutate(fat_content = as.integer(str_replace(fat_content, "%", ""))) |>
  filter(fat_content & calcium_content)


ggplot(cleaned_cheeses, aes(x = fat_content, y = calcium_content)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  labs(
    title = "Fat versus Calcium content of Cheese",
    x = "Fat Content (%)",
    y = "Calcium Content (mg/100g)"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    axis.title = element_text(face = "bold"),
    axis.text = element_text(color = "gray20"),
    panel.grid.major = element_line(color = "gray85"),
    panel.grid.minor = element_blank()
  )
```
